
package Formularios;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author CelesteZaldivar
 */
public class Alerta_dialog extends javax.swing.JDialog {
     public String msj[]=null;
    public Alerta_dialog(javax.swing.JDialog parent, boolean modal) { 
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); 
        ImageIcon img1=new ImageIcon("C:\\Users\\Celeste Zaldivar\\Documents\\NetBeansProjects\\prueba de coexion\\Admin_horas_extras\\src\\iconos\\icono_login.png");
        Image imgEscalada = img1.getImage().getScaledInstance(titulo_alerta.getWidth(),titulo_alerta.getHeight(), Image.SCALE_SMOOTH);
        Icon  iconoEscalado = new ImageIcon(imgEscalada);
        titulo_alerta.setIcon(iconoEscalado);
       
    }
    public void mostrar_txt(String f1,String f2,String f3,String f4)
    {
       this.f_ini_h_e.setText(f1);
       this.f_ingre_peti.setText(f2);
       this.f_fin_h_e.setText(f3);
       this.f_ingre_sy.setText(f4);
    }
    public void msj(String msj1,String msj2,String msj3,String msj4)
    {
        this.txt_mostrar_h_i_h_e.setText(msj1);
        this.txt_mostrar_h_i_p.setText(msj2);
        this.txt_mostrar_h_f_h_e.setText(msj3);
        this.txt_mostrar_h_f_s.setText(msj4);
    }
  
   
            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_alerta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_mostrar_h_i_h_e = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_mostrar_h_i_p = new javax.swing.JLabel();
        txt_mostrar_h_f_s = new javax.swing.JLabel();
        txt_mostrar_h_f_h_e = new javax.swing.JLabel();
        f_ini_h_e = new javax.swing.JLabel();
        f_ingre_peti = new javax.swing.JLabel();
        f_fin_h_e = new javax.swing.JLabel();
        f_ingre_sy = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        msj_2 = new javax.swing.JLabel();
        msj_1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_alerta.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        titulo_alerta.setForeground(new java.awt.Color(51, 51, 51));
        titulo_alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_alerta.setText("Alerta");
        jPanel1.add(titulo_alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 6, -1, 33));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Las fechas de inicio o las fechas final no concuerdan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 40, 410, 40));

        txt_mostrar_h_i_h_e.setForeground(new java.awt.Color(51, 51, 51));
        txt_mostrar_h_i_h_e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mostrar_h_i_h_e.setText("Fecha de inicio Hora extra:");
        jPanel1.add(txt_mostrar_h_i_h_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 159, 24));

        jButton1.setText("Cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        txt_mostrar_h_i_p.setForeground(new java.awt.Color(51, 51, 51));
        txt_mostrar_h_i_p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mostrar_h_i_p.setText("Fecha de ingreso peticion:");
        jPanel1.add(txt_mostrar_h_i_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 159, 24));

        txt_mostrar_h_f_s.setForeground(new java.awt.Color(51, 51, 51));
        txt_mostrar_h_f_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mostrar_h_f_s.setText("Fecha de ingreso SYSAID:");
        jPanel1.add(txt_mostrar_h_f_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 159, 20));

        txt_mostrar_h_f_h_e.setForeground(new java.awt.Color(51, 51, 51));
        txt_mostrar_h_f_h_e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_mostrar_h_f_h_e.setText("Fecha de final Horas extra:");
        jPanel1.add(txt_mostrar_h_f_h_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 159, 24));

        f_ini_h_e.setText("jLabel2");
        jPanel1.add(f_ini_h_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 101, 24));

        f_ingre_peti.setText("jLabel2");
        jPanel1.add(f_ingre_peti, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 24));

        f_fin_h_e.setText("jLabel2");
        jPanel1.add(f_fin_h_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 97, 24));

        f_ingre_sy.setText("jLabel2");
        jPanel1.add(f_ingre_sy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 97, 24));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 440, 10));

        msj_2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msj_2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        msj_2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(msj_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 90));

        msj_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        msj_1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        msj_1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(msj_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 70));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alerta_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alerta_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alerta_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alerta_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Alerta_dialog dialog = new Alerta_dialog(new javax.swing.JDialog(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
          //  dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f_fin_h_e;
    private javax.swing.JLabel f_ingre_peti;
    private javax.swing.JLabel f_ingre_sy;
    private javax.swing.JLabel f_ini_h_e;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel msj_1;
    private javax.swing.JLabel msj_2;
    private javax.swing.JLabel titulo_alerta;
    private javax.swing.JLabel txt_mostrar_h_f_h_e;
    private javax.swing.JLabel txt_mostrar_h_f_s;
    private javax.swing.JLabel txt_mostrar_h_i_h_e;
    private javax.swing.JLabel txt_mostrar_h_i_p;
    // End of variables declaration//GEN-END:variables
}
